// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBemKHI3f0gg3TS3nyBIEPgccrsg4Jgf1Y',
    appId: '1:402979541096:android:531cc4763767d0162e2bdd',
    messagingSenderId: '402979541096',
    projectId: 'solace-rwanda',
    storageBucket: 'solace-rwanda.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJgEji-jXeVBhwiRnjBBk-87Padcwhi08',
    appId: '1:402979541096:ios:b04f5738a1b718752e2bdd',
    messagingSenderId: '402979541096',
    projectId: 'solace-rwanda',
    storageBucket: 'solace-rwanda.firebasestorage.app',
    iosClientId: '402979541096-u9ns7v1jt1bk8t1b5cb1tc970m5d0vm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.solace',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHn1qx51PUtaQUiyLgCcnxMGpJhBe_UCo',
    appId: '1:402979541096:web:a40011f18ac9b7f22e2bdd',
    messagingSenderId: '402979541096',
    projectId: 'solace-rwanda',
    authDomain: 'solace-rwanda.firebaseapp.com',
    storageBucket: 'solace-rwanda.firebasestorage.app',
    measurementId: 'G-H4HBLFYZF3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJgEji-jXeVBhwiRnjBBk-87Padcwhi08',
    appId: '1:402979541096:ios:b04f5738a1b718752e2bdd',
    messagingSenderId: '402979541096',
    projectId: 'solace-rwanda',
    storageBucket: 'solace-rwanda.firebasestorage.app',
    iosClientId: '402979541096-u9ns7v1jt1bk8t1b5cb1tc970m5d0vm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.solace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHn1qx51PUtaQUiyLgCcnxMGpJhBe_UCo',
    appId: '1:402979541096:web:3244df5e273625cf2e2bdd',
    messagingSenderId: '402979541096',
    projectId: 'solace-rwanda',
    authDomain: 'solace-rwanda.firebaseapp.com',
    storageBucket: 'solace-rwanda.firebasestorage.app',
    measurementId: 'G-XZD9W85F8S',
  );
}
